---
abstract: 'Tie a mounted node to an array'
author:
  - 'Steven Schubiger <schubiger@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Tie-Mounted
provides:
  Tie::Mounted:
    file: lib/Tie/Mounted.pm
    version: '0.20'
requires:
  Carp: '0'
  File::Which: '0'
  IO::File: '0'
  Tie::Array: '0'
  boolean: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/stsc/Tie-Mounted
version: '0.20'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
